markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

defaults:
  - values:
      layout: default
      description: |
        Bitbear.org is the website of electronic music producer Asbjørn Ulsberg

sass:
  sass_dir: assets/scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - readme.md
  - .gitignore
  - spec
  - Rakefile
  - coverage
