markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->
url: https://bitbear.music
plugins:
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

author:
  name: Asbjørn Ulsberg
  email: mail@bitbear.music

defaults:
  - values:
      layout: default
      description: |
        bitbear.music is the website of electronic music producer Asbjørn Ulsberg
  - scope:
      path: music/albums
    values:
      layout: album
  - scope:
      path: music
    values:
      layout: post

sass:
  sass_dir: assets/scss
  style: compressed
  sourcemap: never
  silence_deprecations:
    - if-function
  load_paths:
    - node_modules/@picocss/pico/scss

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - LICENSE.txt
  - CODE_OF_CONDUCT.md
  - readme.md
  - .DS_Store
  - .gitignore
  - spec
  - Rakefile
  - coverage
  - package.json
  - package-lock.json
