name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          rubygems: 3.4.10
          bundler-cache: true

      - name: jekyll build
        run: bundle exec rake build

      - name: upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  htmlproofer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site

      - name: htmlproofer
        uses: chabad360/htmlproofer@v2
        with:
          directory: _site
          arguments: --ignore-status-codes "429,302" --ignore-urls "/twitter.com/"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          rubygems: 3.4.10
          bundler-cache: true

      - name: rspec
        run: bundle exec rake spec

      - name: codecov upload
        run: bundle exec rake codecov:upload || echo 'Codecov upload failed'

      - name: rubocop
        run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses

  download-site:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
