name: publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          rubygems: 3.4.10
          bundler-cache: true

      - run: bundle exec rake build

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - id: deployment
        uses: actions/deploy-pages@v3
