name: publish

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: _site

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - id: deployment
        uses: actions/deploy-pages@v3
